### ISSUE TITLE
on UpSync, allow target ns to be defined in annotation/label

### ISSUE THREAD

**Issue by joaocc** [flanksource/vcluster-sync-host-secrets#6]
Hi,
_Reposting from [https://github.com/loft-sh/vcluster-sdk/issues/56]_
_Edited after detecting that it is possible to configure an env variable on the plugin to change the default namespace._

Would it be possible to add an annotation or label with the target namespace to create a specific secret in, in the case of upsync? Even though we can select a default namespace for secrets (via env on the plugin), being able to define this for each secret would make the plugin much more useful... Kind of a cross-cluster-secrets-operator :)
Thx

**Comment by joaocc** [comment]
Thanks. How ofter is the plugin synchronizing secrets? Thx

**Comment by paddatrapper** [comment]
It is controlled by VCluster's reconciliation period, so you'll have to look at what their documentation/code is doing to answer that
